### ISSUE TITLE
Operators in test function don't have highlighting

### ISSUE THREAD

**Issue by ram02z** [krnik/tree-sitter-fish#2]
Using sqaure brackets shows highlighting for operators, but using the test function removes this.

> Example code

![image](https://user-images.githubusercontent.com/59267627/118410937-f1e4a380-b689-11eb-96fa-74abcc8dbc54.png)

> Treesitter Playground output

![image](https://user-images.githubusercontent.com/59267627/118410992-42f49780-b68a-11eb-9172-2c66c4d53533.png)

**Comment by krnik** [comment]
Adjusting the `test_command` grammar rule would do the job:
```
test_command: $ => choice(
    < bracket syntax rule >,
    seq(
        'test',
        optional($._test_expression),
     ),
),
```

I have my doubts whether it should be done, `[ ]` syntax for test is a special case just like in case of [bash grammar](https://github.com/tree-sitter/tree-sitter-bash/blob/7776f24dfa35826fd3038c54a9c311b9e263c22c/grammar.js#L263). I was kinda bored and added rules for the `test` command arguments.

Anyway, making an exception in this case should be all right. I'll add the rule and test cases this week if no-one does it first :]

**Comment by krnik** [comment]
@ram02z I added the change you requested: https://github.com/krnik/tree-sitter-fish/commit/1c25205cd7a68434bd1e576972193b3994404307

Now the input: `test 0 -eq 1` will be represented as:
```scm
(test_command
  (binary_expression
    (integer)
    (test_option)
    (integer)))
```

Let me know if it works for you ; ] And feel free to close the issue if it does.

**Comment by ram02z** [comment]
@krnik Thanks for the change. I had an issue updating it through `TSUpdate`. It seemed to not want to get the latest commit and was stuck on 3e31952b0ef7454b2c52af8e60e4db9b6f43c82f. So, I manually compiled it and got the following error:
`The 'gyp==0.1' distribution was not found and is required by the application`. 
This is probably an issue on my machine becuase once I installed npm-gyp, it compiled fine. Also, the compiled file size went up from 86.2k to 228k.

As for the change, the highlight now appears. The example you gave, `test 0 != 0`, should probably not be parsed the same way since the operators `=` and `!=` are meant to be used on strings, but they do work on integers. Though, it may be best practice to invalidate it.

**Comment by krnik** [comment]
`nvim-treesitter` has hardcoded commit hash of all grammar repos. It's automatically updated from time to time.
 In order to test the newest build of some grammar it's necessary to compile it manually.

In the end, I will hold on with parsing `=` and `!=` as a `test_option`. It's fine the way it is for now :]
